### PR TITLE
fix theta path

### PR DESCRIPTION
**Pull request by fouriaux**
INTEL path: /opt/cray/pe/hdf5/1.10.0/INTEL/16.0/ does not exist on Theta so we replace it by:
 /opt/cray/pe/hdf5/default/INTEL/16.0/ in configuration file.

default is sym link pointing to last updated version of hdf5 : 1.10.0.3.

### CODE REVIEW

**Comment by pramodskumbhar** [comment]
ahh..agree!

one thing that is bit confusing to me is [our Jenkins](https://bbpcode.epfl.ch/ci/view/hpc/job/hpc.spack-packages.github/) didn't triggered from this PR. I wonder this is because you created PR from your fork. In this case we have to look at Jenkins configuration where in `Repositories ->Advanced ` section we specify :

```
Refspec : +refs/pull/*:refs/remotes/origin/pr/*
```

I wonder if this is not matching PR from external repos :|

**Comment by fouriaux** [comment]
@pramod, indeed, 
from what I read online it can be a problem of resource starvation in the sense that Jenkin and travis try to access to same resources together ?

**Review by pramodskumbhar — APPROVED** [review]
@fouriaux : seems like Jenkins and Travis are working fine now.

**Comment by pramod** [comment]
Hi guys,

I am @pramod on Github but not Pramod S Kumbar. :-) Could you please remove
me from this e-mail chain?

Thanks,
Pramod

**Comment by pramodskumbhar** [comment]
Hey @pramod,

My colleague mentioned your handle and hence you ended up receiving all updates. As we have closed this issue, this will be last update and hence you won't receive anymore. Sorry for inconvenience. (in email notification from GitHub there is link "mute the thread" to disable such accidental email notifications).

**Comment by pramod** [comment]
Thanks. The mute thread button doesn't work because I don't have access to
your repository.

**Pull request merged**
